### ISSUE TITLE
Too much whitespace in dropdowns

### ISSUE THREAD

**Issue by bossanova808** [angell-co/Pimp-My-Matrix#25]
I would love it if this menu were a lot more compact...even on my 27" monitor it fills most of the vertical height!

![2015-11-19_14-39-24](https://cloud.githubusercontent.com/assets/731309/11262857/4491c9d0-8ed8-11e5-99b7-2bcabc0f4c6f.png)

**Comment by joshangell** [comment]
Improved in #44

**Comment by bossanova808** [comment]
Hey Josh

Looking forward to trying this with C3!

I still think the whitespace is a lot too much though, personally.  Or possibly some sort of nested organisation would help too...once you have a bunch of types, the drop down is still very large

![image](https://user-images.githubusercontent.com/731309/42249593-7fde4fd8-7f6f-11e8-9ef7-80d217d10737.png)

**Comment by joshangell** [comment]
Moved to the C3 repo, will respond there: https://github.com/angell-co/Spoon/issues/2
