### ISSUE TITLE
Matrix field entries come up blank

### ISSUE THREAD

**Issue by jeremyadams** [angell-co/Pimp-My-Matrix#42]
Chrome will occasionally have an empty entry field when Pimp My Matrix is enabled. On browser resize the field appear. See here: https://www.youtube.com/watch?v=30opqlz8HQ0&feature=youtu.be

**Comment by joshangell** [comment]
What version of PMM are you running?

**Comment by rubenwebs** [comment]
I have the same problem.

PMM: 2.1.4
Craft: 2.6.2791

**Comment by simplethemes** [comment]
I'm having the same issue while using Redactor 1. Is this related?
https://cl.ly/3V0U001T3T24

**Comment by aaronbushnell** [comment]
Same issue:

**Craft** 2.6.2796
**Chrome** 51.0.2704.106
**PMM** 2.1.2

**Comment by joshangell** [comment]
Hi all - sorry you are all experiencing problems with this, we will get around to looking at it at some point but I'm afraid client work has to take priority. If anyone fancies taking a look at it they are more than welcome 😃

**Comment by brianckaufman** [comment]
Yes, we're experiencing this issue as well:

Block not showing content until another block added. When we first add the block we see: http://d.pr/i/yXGk until we add another block and then content for both appears: http://d.pr/i/bN5y.

Chrome v54.0.2840.98; Craft v2.6.2950

**Comment by joshangell** [comment]
Fixed in #51
