### ISSUE TITLE
Disabling matrix fields broken?

### ISSUE THREAD

**Issue by dennisfrank** [angell-co/Pimp-My-Matrix#46]
It seems that disabling of Matrix fields does not work with Matrix fields pimped by PimpMyMatrix.

I can disable fields in the control panel (via the top-right cog drop-down) but this does not affect the the front-end. The _disabled_ field’s content does still show up. 

Could you reproduce this behaviour?

**Comment by dennisfrank** [comment]
Anyone looked into it? At least it would be good to know, if this is a known issue or if it just happens in _my_ installation. Thanks! :wink:

(No reaction is totally ok too. I mean, it’s free software and I am using it without paying you. Thanks for that! :smiley:)

**Comment by joshangell** [comment]
Ha, yes sorry I haven’t looked into it actually at all ... does uninstall PMM solve it?

**Comment by joshangell** [comment]
Hey @dennisfrank did you resolve this at all?

**Comment by dennisfrank** [comment]
So sorry. I've forgot to look into it. I'll let you know when I know more
